#include "PluginEditor.h"
#include "WebData.h" // generated by juce_add_binary_data

namespace
{
    // JUCE 8 calls our provider with a path like "/" (for the root) or
    // "/sim.js" — NOT a full URL. We pick the resource by filename.
    std::optional<juce::WebBrowserComponent::Resource>
    fetchResource (const juce::String& path)
    {
        juce::Logger::writeToLog ("[MyceliumGrove] WebView requested: " + path);

        auto file = path;
        while (file.startsWithChar ('/'))
            file = file.substring (1);
        if (file.isEmpty())
            file = "index.html";

        struct Mapping { const char* file; const char* mime; const char* binaryName; };
        static const Mapping table[] = {
            { "index.html",                "text/html",       "index_html"               },
            { "sim.js",                    "text/javascript", "sim_js"                   },
            { "bridge.js",                 "text/javascript", "bridge_js"                },
            { "styles.css",                "text/css",        "styles_css"               },
            { "jucefrontend.js",           "text/javascript", "jucefrontend_js"          },
            { "check_native_interop.js",   "text/javascript", "check_native_interop_js"  },
        };

        for (auto& m : table)
        {
            if (file == m.file)
            {
                int size = 0;
                const char* data = WebData::getNamedResource (m.binaryName, size);
                if (data == nullptr || size <= 0) break;

                juce::WebBrowserComponent::Resource r;
                const auto* bytes = reinterpret_cast<const std::byte*> (data);
                r.data.assign (bytes, bytes + size);
                r.mimeType = m.mime;
                return r;
            }
        }
        return std::nullopt;
    }
}

juce::WebBrowserComponent::Options MyceliumGroveEditor::buildWebOptions()
{
    using Options = juce::WebBrowserComponent::Options;

    auto opts = Options{}
       #if JUCE_WINDOWS
        .withBackend (Options::Backend::webview2)
        .withWinWebView2Options (Options::WinWebView2{}
            .withUserDataFolder (juce::File::getSpecialLocation (juce::File::tempDirectory)))
       #endif
        .withResourceProvider ([] (const juce::String& path) { return fetchResource (path); })
        .withNativeIntegrationEnabled (true)
        .withNativeFunction ("seedSpore",
            [this] (const juce::Array<juce::var>& args,
                    juce::WebBrowserComponent::NativeFunctionCompletion completion)
            { handleSeedSpore (args, std::move (completion)); })
        .withNativeFunction ("bondFormed",
            [this] (const juce::Array<juce::var>& args,
                    juce::WebBrowserComponent::NativeFunctionCompletion completion)
            { handleBondFormed (args, std::move (completion)); })
        .withNativeFunction ("bridgeReady",
            [] (const juce::Array<juce::var>& args,
                juce::WebBrowserComponent::NativeFunctionCompletion completion)
            {
                juce::String marker = args.size() > 0 ? args[0].toString() : juce::String();
                juce::Logger::writeToLog ("[bridge] ready ping from JS: " + marker);
                completion ("ok");
            });

    // Wire each APVTS parameter to a relay so the JS side can subscribe.
    auto& apvts = proc.getApvts();

    auto wireSlider = [&] (const juce::String& id)
    {
        auto relay = std::make_unique<juce::WebSliderRelay> (id);
        opts = opts.withOptionsFrom (*relay);
        if (auto* p = apvts.getParameter (id))
            sliderAttachments.push_back (
                std::make_unique<juce::WebSliderParameterAttachment> (*p, *relay, nullptr));
        sliderRelays.push_back (std::move (relay));
    };

    auto wireToggle = [&] (const juce::String& id)
    {
        auto relay = std::make_unique<juce::WebToggleButtonRelay> (id);
        opts = opts.withOptionsFrom (*relay);
        if (auto* p = apvts.getParameter (id))
            toggleAttachments.push_back (
                std::make_unique<juce::WebToggleButtonParameterAttachment> (*p, *relay, nullptr));
        toggleRelays.push_back (std::move (relay));
    };

    auto wireChoice = [&] (const juce::String& id)
    {
        auto relay = std::make_unique<juce::WebComboBoxRelay> (id);
        opts = opts.withOptionsFrom (*relay);
        if (auto* p = apvts.getParameter (id))
            choiceAttachments.push_back (
                std::make_unique<juce::WebComboBoxParameterAttachment> (*p, *relay, nullptr));
        choiceRelays.push_back (std::move (relay));
    };

    wireToggle ("rainOn");
    wireSlider ("rainRate");
    wireSlider ("bondRadius");
    wireSlider ("branchProb");
    wireChoice ("scale");
    wireChoice ("root");
    wireSlider ("octave");
    wireSlider ("masterGain");
    wireSlider ("reverbWet");
    wireSlider ("lowpassHz");
    wireSlider ("padLevel");
    wireSlider ("pluckLevel");
    wireSlider ("thumpLevel");
    wireToggle ("freezeOnStop");

    return opts;
}

MyceliumGroveEditor::MyceliumGroveEditor (MyceliumGroveProcessor& p)
    : AudioProcessorEditor (&p),
      proc (p),
      webView (buildWebOptions())
{
    setSize (820, 540);
    setResizable (true, true);
    setResizeLimits (480, 320, 3840, 2160);

    addAndMakeVisible (webView);
    juce::Logger::writeToLog ("[editor] opening URL: " + juce::WebBrowserComponent::getResourceProviderRoot());
    webView.goToURL (juce::WebBrowserComponent::getResourceProviderRoot());
}

MyceliumGroveEditor::~MyceliumGroveEditor() = default;

void MyceliumGroveEditor::paint (juce::Graphics& g)
{
    // The WebView covers the whole bounds; this only matters during reflow.
    g.fillAll (juce::Colour::fromRGB (0x06, 0x05, 0x0d));
}

void MyceliumGroveEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

juce::var MyceliumGroveEditor::handleSeedSpore (const juce::Array<juce::var>& args,
                                                juce::WebBrowserComponent::NativeFunctionCompletion completion)
{
    // bridge.js sends: hue, timestamp, velocity, pan
    const float hue      = (args.size() > 0) ? (float) (double) args[0] : 0.0f;
    const float velocity = (args.size() > 2) ? juce::jlimit (0.0f, 1.0f, (float) (double) args[2]) : 0.9f;
    const float pan      = (args.size() > 3) ? juce::jlimit (-1.0f, 1.0f, (float) (double) args[3]) : 0.0f;
    proc.getQueue().pushSpore (hue, velocity, pan);
    completion ("ok");
    return {};
}

juce::var MyceliumGroveEditor::handleBondFormed (const juce::Array<juce::var>& args,
                                                 juce::WebBrowserComponent::NativeFunctionCompletion completion)
{
    // bridge.js sends: hueA, hueB, timestamp, velocity, pan
    const float hueA     = (args.size() > 0) ? (float) (double) args[0] : 0.0f;
    const float hueB     = (args.size() > 1) ? (float) (double) args[1] : 0.0f;
    const float velocity = (args.size() > 3) ? juce::jlimit (0.0f, 1.0f, (float) (double) args[3]) : 0.7f;
    const float pan      = (args.size() > 4) ? juce::jlimit (-1.0f, 1.0f, (float) (double) args[4]) : 0.0f;
    proc.getQueue().pushBond (hueA, hueB, 0.0f, velocity, pan); // pitch recomputed on audio thread
    completion ("ok");
    return {};
}
